services:
  mysql:
    container_name: wd_mysql
    env_file: .env
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    networks:
      development:
        ipv4_address: "172.20.0.4"

  wordpress:
    container_name: wd_wp
    env_file: .env
    image: wordpress:latest
    ports:
      - 8080:80
    depends_on:
      - mysql
    volumes:
      - wordpress:${WORDPRESS_PATH}/
      - ./work_dir/plugins:${WORDPRESS_PATH}/wp-content/plugins
      - plugins:${WORDPRESS_PATH}/wp-content/plugins
    networks:
      development:
        ipv4_address: "172.20.0.2"

    develop:
      watch:
        - action: sync+restart
          path: ./work_dir/plugins
          target: ${WORDPRESS_PATH}/wp-content/plugins

  wpcli:
    container_name: wd_wpcli
    env_file: .env
    image: wd/wpcli:develop
    build:
      context: ./dockerfiles/wpcli
    depends_on:
      - mysql
      - wordpress
    volumes:
      - wordpress:${WORDPRESS_PATH}/
      - ./work_dir/plugins:${WORDPRESS_PATH}/wp-content/plugins
      - plugins:${WORDPRESS_PATH}/wp-content/plugins
    networks:
      development:
        ipv4_address: "172.20.0.3"

    develop:
      watch:
        - action: sync+restart
          path: ./dockerfiles/wpcli/init
          target: /tmp/init

  phpmyadmin:
    container_name: wd_phpmyadmin
    env_file: .env
    image: phpmyadmin:latest
    ports:
      - "8181:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      development:
        ipv4_address: "172.20.0.5"

volumes:
  wordpress:
  plugins:
  mysql:

networks:
  development:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
