services:
  mysql:
    container_name: wd_mysql
    env_file: .env
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql

  wordpress:
    container_name: wd_wp
    env_file: .env
    image: wordpress:latest
    ports:
      - 8080:80
    depends_on:
      - mysql
    volumes:
      - wordpress:${WORDPRESS_PATH}/
      - ./work_dir/plugins/${PLUGIN_NAME}:${WORDPRESS_PATH}/wp-content/plugins/${PLUGIN_NAME}
      - plugins:${WORDPRESS_PATH}/wp-content/plugins

    develop:
      watch:
        - action: sync+restart
          path: ./work_dir/plugins
          target: ${WORDPRESS_PATH}/wp-content/plugins

  wpcli:
    container_name: wd_wpcli
    env_file: .env
    image: wd/wpcli:develop
    build:
      context: ./dockerfiles/wpcli
    depends_on:
      - mysql
      - wordpress
    volumes:
      - wordpress:${WORDPRESS_PATH}/
      - ./work_dir/plugins/${PLUGIN_NAME}:${WORDPRESS_PATH}/wp-content/plugins/${PLUGIN_NAME}
      - plugins:${WORDPRESS_PATH}/wp-content/plugins

    develop:
      watch:
        - action: sync+restart
          path: ./dockerfiles/wpcli/init
          target: /tmp/init

  phpmyadmin:
    container_name: wd_phpmyadmin
    env_file: .env
    image: phpmyadmin:latest
    ports:
      - "8181:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
  wordpress:
  plugins:
  mysql:
