name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build pre-configured WordPress CLI Docker image
        run: docker build ./dockerfiles/wpcli/ --file ./dockerfiles/wpcli/Dockerfile --tag wd-wpcli:$(date +%s)

        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
